package com.mingyuansoftware.aifactory.service;

import com.mingyuansoftware.aifactory.model.StaffGroupAccess;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StaffGroupAccessService {
    int deleteByPrimaryKey(@Param("groupId") Integer groupId, @Param("accessId") Integer accessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_group_access
     *
     * @mbggenerated
     */
    int insert(StaffGroupAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_group_access
     *
     * @mbggenerated
     */
    StaffGroupAccess selectByPrimaryKey(@Param("groupId") Integer groupId, @Param("accessId") Integer accessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_group_access
     *
     * @mbggenerated
     */
    List<StaffGroupAccess> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_group_access
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaffGroupAccess record);
}
