/**
 * Copyright (C), 2019-2019, 天津斯睿曼科技有限公司
 * FileName: StaffAccessService
 * Author:   EDZ
 * Date:     2019/7/24 10:09
 * Description: 员工权限
 * History:
 * <author>          <time>          <version>          <desc>
 * 作者姓名           修改时间           版本号              描述
 */
package com.mingyuansoftware.aifactory.service;

import com.mingyuansoftware.aifactory.model.StaffAccess;

import java.util.List;

/**
 * 〈一句话功能简述〉<br> 
 * 〈员工权限〉
 *
 * @author EDZ
 * @create 2019/7/24
 * @since 1.0.0
 */
public interface StaffAccessService {

    int deleteByPrimaryKey(Integer accessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_access
     *
     * @mbggenerated
     */
    int insert(StaffAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_access
     *
     * @mbggenerated
     */
    StaffAccess selectByPrimaryKey(Integer accessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_access
     *
     * @mbggenerated
     */
    List<StaffAccess> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_access
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaffAccess record);

    List<StaffAccess> selectByParId(Integer accessId);

}
