package com.mingyuansoftware.aifactory.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;

@ApiModel(description = "张婷")
public class WarehousePosition implements Serializable {

    @ApiModelProperty(value = "仓位id", example = "1")
    private Integer wpId;

    @ApiModelProperty(value = "仓位名称", example = "仓位名称")
    private String wpName;

    @ApiModelProperty(value = "仓库id", example = "1")
    private Integer warehouseId;

    @ApiModelProperty(value = "状态 1.表示空闲 2.表示使用中", example = "1")
    private Byte state;

    @ApiModelProperty(value = "创建时间", example = "createTime")
    private Date createTime;

    @ApiModelProperty(value = "修改时间", example = "updateTime")
    private Date updateTime;

    @ApiModelProperty(value = "备注", example = "备注")
    private String comment;

    @ApiModelProperty(value = "删除状态 1.表示删除 0.表示未删除", example = "0")
    private Byte isDelete;

    private static final long serialVersionUID = 1L;

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_position.wp_id
     *
     * @return the value of warehouse_position.wp_id
     * @mbggenerated
     */
    public Integer getWpId() {
        return wpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_position.wp_id
     *
     * @param wpId the value for warehouse_position.wp_id
     * @mbggenerated
     */
    public void setWpId(Integer wpId) {
        this.wpId = wpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_position.wp_name
     *
     * @return the value of warehouse_position.wp_name
     * @mbggenerated
     */
    public String getWpName() {
        return wpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_position.wp_name
     *
     * @param wpName the value for warehouse_position.wp_name
     * @mbggenerated
     */
    public void setWpName(String wpName) {
        this.wpName = wpName == null ? null : wpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_position.warehouse_id
     *
     * @return the value of warehouse_position.warehouse_id
     * @mbggenerated
     */
    public Integer getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_position.warehouse_id
     *
     * @param warehouseId the value for warehouse_position.warehouse_id
     * @mbggenerated
     */
    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_position.state
     *
     * @return the value of warehouse_position.state
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_position.state
     *
     * @param state the value for warehouse_position.state
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_position.create_time
     *
     * @return the value of warehouse_position.create_time
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_position.create_time
     *
     * @param createTime the value for warehouse_position.create_time
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_position.update_time
     *
     * @return the value of warehouse_position.update_time
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_position.update_time
     *
     * @param updateTime the value for warehouse_position.update_time
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_position.is_delete
     *
     * @return the value of warehouse_position.is_delete
     * @mbggenerated
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_position.is_delete
     *
     * @param isDelete the value for warehouse_position.is_delete
     * @mbggenerated
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_position
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        return "WarehousePosition{" +
                "wpId=" + wpId +
                ", wpName='" + wpName + '\'' +
                ", warehouseId=" + warehouseId +
                ", state=" + state +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", comment='" + comment + '\'' +
                ", isDelete=" + isDelete +
                '}';
    }
}