/**
 * Copyright (C), 2019-2019, 天津斯睿曼科技有限公司
 * FileName: ReceiptDto
 * Author:   EDZ
 * Date:     2019/7/17 16:18
 * Description: 收款单
 * History:
 * <author>          <time>          <version>          <desc>
 * 作者姓名           修改时间           版本号              描述
 */
package com.mingyuansoftware.aifactory.model.dto;

import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;

/**
 * 〈一句话功能简述〉<br> 
 * 〈收款单〉
 *
 * @author EDZ
 * @create 2019/7/17
 * @since 1.0.0
 */
public class ReceiptDto
{
    @ApiModelProperty(value = "收款单id", example = "1")
    private Integer receiptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.receipt_number
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "编号", example = "221")
    private String receiptNumber;

    @ApiModelProperty(value = "收款类别", example = "销售收款")
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.payer
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "付款方", example = "小王")
    private String payer;


    @ApiModelProperty(value = "收款金额", example = "1.11")
    private BigDecimal collectionAmount;


    @ApiModelProperty(value = "备注", example = "备注")
    private String comment;



    @ApiModelProperty(value = "创建时间", example = "2018-03-04")
    private String cjTime;

    @ApiModelProperty(value = "创建人", example = "")
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getReceiptId() {
        return receiptId;
    }

    public void setReceiptId(Integer receiptId) {
        this.receiptId = receiptId;
    }

    public String getReceiptNumber() {
        return receiptNumber;
    }

    public void setReceiptNumber(String receiptNumber) {
        this.receiptNumber = receiptNumber;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getPayer() {
        return payer;
    }

    public void setPayer(String payer) {
        this.payer = payer;
    }

    public BigDecimal getCollectionAmount() {
        return collectionAmount;
    }

    public void setCollectionAmount(BigDecimal collectionAmount) {
        this.collectionAmount = collectionAmount;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getCjTime() {
        return cjTime;
    }

    public void setCjTime(String cjTime) {
        this.cjTime = cjTime;
    }
}
