package com.mingyuansoftware.aifactory.model.dto;

import com.mingyuansoftware.aifactory.model.StaffAccess;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

@ApiModel(description="王力影")
public class StaffAccessGroupDto implements Serializable {


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_access_group.group_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "权限组名称", example = "管理员")
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_access_group.group_text
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "权限组描述", example = "管理员")
    private String groupText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_access_group.add_time
     *
     * @mbggenerated
     */



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table staff_access_group
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_access_group.group_id
     *
     * @return the value of staff_access_group.group_id
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_access_group.group_name
     *
     * @return the value of staff_access_group.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_access_group.group_name
     *
     * @param groupName the value for staff_access_group.group_name
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_access_group.group_text
     *
     * @return the value of staff_access_group.group_text
     *
     * @mbggenerated
     */
    public String getGroupText() {
        return groupText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_access_group.group_text
     *
     * @param groupText the value for staff_access_group.group_text
     *
     * @mbggenerated
     */
    public void setGroupText(String groupText) {
        this.groupText = groupText == null ? null : groupText.trim();
    }

}