package com.mingyuansoftware.aifactory.mapper;

import com.mingyuansoftware.aifactory.model.SupplierGoods;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.util.List;
@Repository
@Mapper
public interface SupplierGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_goods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer supplierGoodsId);


    int deleteKey(Integer supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_goods
     *
     * @mbggenerated
     */
    int insert(SupplierGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_goods
     *
     * @mbggenerated
     */
    List<SupplierGoods> selectByPrimaryKey(Integer supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_goods
     *
     * @mbggenerated
     */
    List<SupplierGoods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SupplierGoods record);

    /**
     * 根据供应商名称和部品cd查询供应商id
     * @param supplerName
     * @param partsCD
     * @return
     */
    SupplierGoods selectSupplierByNameAndPartsCD(@Param("supplerName") String supplerName,@Param("partsCD") String partsCD);

    /**
     * 先根据供应商Id和货物Id查询供应商货物表中的内容
     * @param supplierId
     * @param partsCd
     * @return
     */
    SupplierGoods selectSuGoodsBySuIdAndGoodsId(@Param("supplierId") Integer supplierId,@Param("partsCd") String partsCd);

    /**
     * 根据供应商Id和部品CD修改供应过的货物数量(叠加)
     * @param supplierGoods
     */
    void updateQuantityBy(@Param("supplierGoods") SupplierGoods supplierGoods);
}