package com.mingyuansoftware.aifactory.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;

@ApiModel(description = "王力影")
public class AdjustRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjust_record.id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "id", example = "1")
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjust_record.job
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "岗位", example = "讲师")
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjust_record.dept
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "部门", example = "培训部")
    private String dept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjust_record.createtime
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "时间", example = "2018-09-01")
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjust_record.staff_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "员工id", example = "1")
    private Integer staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjust_record.comment
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "备注", example = "")
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table adjust_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjust_record.id
     *
     * @return the value of adjust_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjust_record.id
     *
     * @param id the value for adjust_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjust_record.job
     *
     * @return the value of adjust_record.job
     *
     * @mbggenerated
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjust_record.job
     *
     * @param job the value for adjust_record.job
     *
     * @mbggenerated
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjust_record.dept
     *
     * @return the value of adjust_record.dept
     *
     * @mbggenerated
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjust_record.dept
     *
     * @param dept the value for adjust_record.dept
     *
     * @mbggenerated
     */
    public void setDept(String dept) {
        this.dept = dept == null ? null : dept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjust_record.createtime
     *
     * @return the value of adjust_record.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjust_record.createtime
     *
     * @param createtime the value for adjust_record.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjust_record.staff_id
     *
     * @return the value of adjust_record.staff_id
     *
     * @mbggenerated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjust_record.staff_id
     *
     * @param staffId the value for adjust_record.staff_id
     *
     * @mbggenerated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjust_record.comment
     *
     * @return the value of adjust_record.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjust_record.comment
     *
     * @param comment the value for adjust_record.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjust_record
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", job=").append(job);
        sb.append(", dept=").append(dept);
        sb.append(", createtime=").append(createtime);
        sb.append(", staffId=").append(staffId);
        sb.append(", comment=").append(comment);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}