package com.mingyuansoftware.aifactory.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
@ApiModel(description = "王力影")
public class InventoryCheck implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_check.inventory_check_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "库存盘点id", example = "1")
    private Integer inventoryCheckId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_check.inventory_check_number
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "编号", example = "134")
    private String inventoryCheckNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_check.warehouse_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "仓库id", example = "1")
    private Integer warehouseId;


    @ApiModelProperty(value = "仓库名称", example = "1")
    private String warehouseName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_check.staff_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "员工id", example = "1")
    private Integer staffId;

    @ApiModelProperty(value = "员工姓名", example = "1")
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_check.state
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "当前状态1为已创建2为已盘点", example = "0")
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_check.create_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "创建时间", example = "")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_check.update_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "修改时间", example = "")
    private Date updateTime;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_check.is_delete
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "是否删除 1是 0否", example = "0")
    private Byte isDelete;
    @ApiModelProperty(value = "发起时间", example = "2018-03-04")
    private String fqTime;

    @ApiModelProperty(value = "备注", example = "备注")
    private String comment;

    public String getWarehouseName() {
        return warehouseName;
    }

    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getFqTime() {
        return fqTime;
    }

    public void setFqTime(String fqTime) {
        this.fqTime = fqTime;
    }

    @ApiModelProperty(value = "盘点库存详情表", example = "inventoryCheckGoods")
    private List<InventoryCheckGoods> inventoryCheckGoods;

    public List<InventoryCheckGoods> getInventoryCheckGoods() {
        return inventoryCheckGoods;
    }

    public void setInventoryCheckGoods(List<InventoryCheckGoods> inventoryCheckGoods) {
        this.inventoryCheckGoods = inventoryCheckGoods;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inventory_check
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_check.inventory_check_id
     *
     * @return the value of inventory_check.inventory_check_id
     *
     * @mbggenerated
     */
    public Integer getInventoryCheckId() {
        return inventoryCheckId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_check.inventory_check_id
     *
     * @param inventoryCheckId the value for inventory_check.inventory_check_id
     *
     * @mbggenerated
     */
    public void setInventoryCheckId(Integer inventoryCheckId) {
        this.inventoryCheckId = inventoryCheckId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_check.inventory_check_number
     *
     * @return the value of inventory_check.inventory_check_number
     *
     * @mbggenerated
     */
    public String getInventoryCheckNumber() {
        return inventoryCheckNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_check.inventory_check_number
     *
     * @param inventoryCheckNumber the value for inventory_check.inventory_check_number
     *
     * @mbggenerated
     */
    public void setInventoryCheckNumber(String inventoryCheckNumber) {
        this.inventoryCheckNumber = inventoryCheckNumber == null ? null : inventoryCheckNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_check.warehouse_id
     *
     * @return the value of inventory_check.warehouse_id
     *
     * @mbggenerated
     */
    public Integer getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_check.warehouse_id
     *
     * @param warehouseId the value for inventory_check.warehouse_id
     *
     * @mbggenerated
     */
    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_check.staff_id
     *
     * @return the value of inventory_check.staff_id
     *
     * @mbggenerated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_check.staff_id
     *
     * @param staffId the value for inventory_check.staff_id
     *
     * @mbggenerated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_check.state
     *
     * @return the value of inventory_check.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_check.state
     *
     * @param state the value for inventory_check.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_check.create_time
     *
     * @return the value of inventory_check.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_check.create_time
     *
     * @param createTime the value for inventory_check.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_check.update_time
     *
     * @return the value of inventory_check.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_check.update_time
     *
     * @param updateTime the value for inventory_check.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_check.is_delete
     *
     * @return the value of inventory_check.is_delete
     *
     * @mbggenerated
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_check.is_delete
     *
     * @param isDelete the value for inventory_check.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_check
     *
     * @mbggenerated
     */

}