package com.mingyuansoftware.aifactory.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.math.BigDecimal;
@ApiModel(description = "王力影")
public class InventoryCheckGoods implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_check_goods.inventory_check_goods_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "库存盘点id", example = "1")
    private Integer inventoryCheckGoodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_check_goods.inventory_check_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "库存盘点id", example = "1")
    private Integer inventoryCheckId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_check_goods.goods_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "库存盘点id", example = "1")
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_check_goods.stock_quantity
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "库存数量", example = "1")
    private BigDecimal stockQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_check_goods.inventory_quantity
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "盘点数量", example = "1")
    private BigDecimal inventoryQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_check_goods.surplus_quantity
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "盘盈数量", example = "1")
    private BigDecimal surplusQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_check_goods.deficit_quantity
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "盘亏数量", example = "1")
    private BigDecimal deficitQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_check_goods.warehouse_position
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "仓位", example = "仓位1")
    private String warehousePosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_check_goods.staff_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "盘点人id", example = "1")
    private Integer staffId;

    @ApiModelProperty(value = "盘点人姓名", example = "小王")
    private String name;

    private Integer pdaState;

    @ApiModelProperty(value = "货物", example = "goods")
    private Goods goods;

    public Integer getPdaState() {
        return pdaState;
    }

    public void setPdaState(Integer pdaState) {
        this.pdaState = pdaState;
    }

    public Goods getGoods() {
        return goods;
    }

    public void setGoods(Goods goods) {
        this.goods = goods;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inventory_check_goods
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_check_goods.inventory_check_goods_id
     *
     * @return the value of inventory_check_goods.inventory_check_goods_id
     *
     * @mbggenerated
     */
    public Integer getInventoryCheckGoodsId() {
        return inventoryCheckGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_check_goods.inventory_check_goods_id
     *
     * @param inventoryCheckGoodsId the value for inventory_check_goods.inventory_check_goods_id
     *
     * @mbggenerated
     */
    public void setInventoryCheckGoodsId(Integer inventoryCheckGoodsId) {
        this.inventoryCheckGoodsId = inventoryCheckGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_check_goods.inventory_check_id
     *
     * @return the value of inventory_check_goods.inventory_check_id
     *
     * @mbggenerated
     */
    public Integer getInventoryCheckId() {
        return inventoryCheckId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_check_goods.inventory_check_id
     *
     * @param inventoryCheckId the value for inventory_check_goods.inventory_check_id
     *
     * @mbggenerated
     */
    public void setInventoryCheckId(Integer inventoryCheckId) {
        this.inventoryCheckId = inventoryCheckId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_check_goods.goods_id
     *
     * @return the value of inventory_check_goods.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_check_goods.goods_id
     *
     * @param goodsId the value for inventory_check_goods.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_check_goods.stock_quantity
     *
     * @return the value of inventory_check_goods.stock_quantity
     *
     * @mbggenerated
     */
    public BigDecimal getStockQuantity() {
        return stockQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_check_goods.stock_quantity
     *
     * @param stockQuantity the value for inventory_check_goods.stock_quantity
     *
     * @mbggenerated
     */
    public void setStockQuantity(BigDecimal stockQuantity) {
        this.stockQuantity = stockQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_check_goods.inventory_quantity
     *
     * @return the value of inventory_check_goods.inventory_quantity
     *
     * @mbggenerated
     */
    public BigDecimal getInventoryQuantity() {
        return inventoryQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_check_goods.inventory_quantity
     *
     * @param inventoryQuantity the value for inventory_check_goods.inventory_quantity
     *
     * @mbggenerated
     */
    public void setInventoryQuantity(BigDecimal inventoryQuantity) {
        this.inventoryQuantity = inventoryQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_check_goods.surplus_quantity
     *
     * @return the value of inventory_check_goods.surplus_quantity
     *
     * @mbggenerated
     */
    public BigDecimal getSurplusQuantity() {
        return surplusQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_check_goods.surplus_quantity
     *
     * @param surplusQuantity the value for inventory_check_goods.surplus_quantity
     *
     * @mbggenerated
     */
    public void setSurplusQuantity(BigDecimal surplusQuantity) {
        this.surplusQuantity = surplusQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_check_goods.deficit_quantity
     *
     * @return the value of inventory_check_goods.deficit_quantity
     *
     * @mbggenerated
     */
    public BigDecimal getDeficitQuantity() {
        return deficitQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_check_goods.deficit_quantity
     *
     * @param deficitQuantity the value for inventory_check_goods.deficit_quantity
     *
     * @mbggenerated
     */
    public void setDeficitQuantity(BigDecimal deficitQuantity) {
        this.deficitQuantity = deficitQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_check_goods.warehouse_position
     *
     * @return the value of inventory_check_goods.warehouse_position
     *
     * @mbggenerated
     */
    public String getWarehousePosition() {
        return warehousePosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_check_goods.warehouse_position
     *
     * @param warehousePosition the value for inventory_check_goods.warehouse_position
     *
     * @mbggenerated
     */
    public void setWarehousePosition(String warehousePosition) {
        this.warehousePosition = warehousePosition == null ? null : warehousePosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_check_goods.staff_id
     *
     * @return the value of inventory_check_goods.staff_id
     *
     * @mbggenerated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_check_goods.staff_id
     *
     * @param staffId the value for inventory_check_goods.staff_id
     *
     * @mbggenerated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_check_goods
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", inventoryCheckGoodsId=").append(inventoryCheckGoodsId);
        sb.append(", inventoryCheckId=").append(inventoryCheckId);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", stockQuantity=").append(stockQuantity);
        sb.append(", inventoryQuantity=").append(inventoryQuantity);
        sb.append(", surplusQuantity=").append(surplusQuantity);
        sb.append(", deficitQuantity=").append(deficitQuantity);
        sb.append(", warehousePosition=").append(warehousePosition);
        sb.append(", staffId=").append(staffId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}