package com.mingyuansoftware.aifactory.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
@ApiModel(description = "王力影")
public class Reimburse implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse.reimburse_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "报销单id", example = "1")
    private Integer reimburseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse.reimburse_number
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "报销单编号", example = "581")
    private String reimburseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse.create_staff_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "报销人id", example = "1")
    private String createStaffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse.review_staff_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "审核人id", example = "1")
    private Integer reviewStaffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse.application_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "申请时间", example = "2018-03-04")
    private String applicationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse.amount
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "金额", example = "1.25")
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse.state
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "状态1.已创建2.已付款3.已审核", example = "1")
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse.comment
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "备注", example = "122")
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse.is_delete
     *
     * @mbggenerated
     */

    private Byte isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse.create_time
     *
     * @mbggenerated
     */

    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse.update_time
     *
     * @mbggenerated
     */

    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reimburse
     *
     * @mbggenerated
     */

    private String createName;

    private String reviewName;

    public String getCreateName() {
        return createName;
    }

    public void setCreateName(String createName) {
        this.createName = createName;
    }

    public String getReviewName() {
        return reviewName;
    }

    public void setReviewName(String reviewName) {
        this.reviewName = reviewName;
    }

    private List<ReimburseDetails> reimburseDetails;

    public List<ReimburseDetails> getReimburseDetails() {
        return reimburseDetails;
    }

    public void setReimburseDetails(List<ReimburseDetails> reimburseDetails) {
        this.reimburseDetails = reimburseDetails;
    }

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimburse.reimburse_id
     *
     * @return the value of reimburse.reimburse_id
     *
     * @mbggenerated
     */
    public Integer getReimburseId() {
        return reimburseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse.reimburse_id
     *
     * @param reimburseId the value for reimburse.reimburse_id
     *
     * @mbggenerated
     */
    public void setReimburseId(Integer reimburseId) {
        this.reimburseId = reimburseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimburse.reimburse_number
     *
     * @return the value of reimburse.reimburse_number
     *
     * @mbggenerated
     */
    public String getReimburseNumber() {
        return reimburseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse.reimburse_number
     *
     * @param reimburseNumber the value for reimburse.reimburse_number
     *
     * @mbggenerated
     */
    public void setReimburseNumber(String reimburseNumber) {
        this.reimburseNumber = reimburseNumber == null ? null : reimburseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimburse.create_staff_id
     *
     * @return the value of reimburse.create_staff_id
     *
     * @mbggenerated
     */
    public String getCreateStaffId() {
        return createStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse.create_staff_id
     *
     * @param createStaffId the value for reimburse.create_staff_id
     *
     * @mbggenerated
     */
    public void setCreateStaffId(String createStaffId) {
        this.createStaffId = createStaffId == null ? null : createStaffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimburse.review_staff_id
     *
     * @return the value of reimburse.review_staff_id
     *
     * @mbggenerated
     */
    public Integer getReviewStaffId() {
        return reviewStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse.review_staff_id
     *
     * @param reviewStaffId the value for reimburse.review_staff_id
     *
     * @mbggenerated
     */
    public void setReviewStaffId(Integer reviewStaffId) {
        this.reviewStaffId = reviewStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimburse.application_time
     *
     * @return the value of reimburse.application_time
     *
     * @mbggenerated
     */
    public String getApplicationTime() {
        return applicationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse.application_time
     *
     * @param applicationTime the value for reimburse.application_time
     *
     * @mbggenerated
     */
    public void setApplicationTime(String applicationTime) {
        this.applicationTime = applicationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimburse.amount
     *
     * @return the value of reimburse.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse.amount
     *
     * @param amount the value for reimburse.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimburse.state
     *
     * @return the value of reimburse.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse.state
     *
     * @param state the value for reimburse.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimburse.comment
     *
     * @return the value of reimburse.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse.comment
     *
     * @param comment the value for reimburse.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimburse.is_delete
     *
     * @return the value of reimburse.is_delete
     *
     * @mbggenerated
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse.is_delete
     *
     * @param isDelete the value for reimburse.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimburse.create_time
     *
     * @return the value of reimburse.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse.create_time
     *
     * @param createTime the value for reimburse.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimburse.update_time
     *
     * @return the value of reimburse.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse.update_time
     *
     * @param updateTime the value for reimburse.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reimburse
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", reimburseId=").append(reimburseId);
        sb.append(", reimburseNumber=").append(reimburseNumber);
        sb.append(", createStaffId=").append(createStaffId);
        sb.append(", reviewStaffId=").append(reviewStaffId);
        sb.append(", applicationTime=").append(applicationTime);
        sb.append(", amount=").append(amount);
        sb.append(", state=").append(state);
        sb.append(", comment=").append(comment);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}