package com.mingyuansoftware.aifactory.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
@ApiModel(description="王力影")
public class StaffAccessGroup implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_access_group.group_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "权限组id", example = "1")
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_access_group.group_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "权限组名称", example = "管理员")
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_access_group.group_text
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "权限组描述", example = "管理员")
    private String groupText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_access_group.add_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "新增时间", example = "2018-03-04")
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_access_group.staff_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "员工id", example = "1")
    private Integer staffId;

    private List<Integer> accessIds;

    private List<StaffAccess> accessTree;

    public List<StaffAccess> getAccessTree() {
        return accessTree;
    }

    public void setAccessTree(List<StaffAccess> accessTree) {
        this.accessTree = accessTree;
    }

    public List<Integer> getAccessIds() {
        return accessIds;
    }

    public void setAccessIds(List<Integer> accessIds) {
        this.accessIds = accessIds;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table staff_access_group
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_access_group.group_id
     *
     * @return the value of staff_access_group.group_id
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_access_group.group_id
     *
     * @param groupId the value for staff_access_group.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_access_group.group_name
     *
     * @return the value of staff_access_group.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_access_group.group_name
     *
     * @param groupName the value for staff_access_group.group_name
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_access_group.group_text
     *
     * @return the value of staff_access_group.group_text
     *
     * @mbggenerated
     */
    public String getGroupText() {
        return groupText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_access_group.group_text
     *
     * @param groupText the value for staff_access_group.group_text
     *
     * @mbggenerated
     */
    public void setGroupText(String groupText) {
        this.groupText = groupText == null ? null : groupText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_access_group.add_time
     *
     * @return the value of staff_access_group.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_access_group.add_time
     *
     * @param addTime the value for staff_access_group.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_access_group.staff_id
     *
     * @return the value of staff_access_group.staff_id
     *
     * @mbggenerated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_access_group.staff_id
     *
     * @param staffId the value for staff_access_group.staff_id
     *
     * @mbggenerated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_access_group
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", groupId=").append(groupId);
        sb.append(", groupName=").append(groupName);
        sb.append(", groupText=").append(groupText);
        sb.append(", addTime=").append(addTime);
        sb.append(", staffId=").append(staffId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}