package com.mingyuansoftware.aifactory.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
@ApiModel(description="王力影")
public class StaffAccess implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_access.access_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "权限主键id", example = "1")
    private Integer accessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_access.access_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "权限名称", example = "accessName")
    private String accessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_access.access_module_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "所属权限模块id", example="1")
    private Integer accessModuleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_access.url
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "url", example="url")
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_access.permissions
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "权限", example = "permissions")
    private String permissions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_access.type
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "权限类型1菜单,2按钮,3其他", example="1")
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_access.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_access.staff_id
     *
     * @mbggenerated
     */
    private Integer staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table staff_access
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    @ApiModelProperty(value = "标识", example="0")
    private Integer mark;

    public Integer getMark() {
        return mark;
    }

    public void setMark(Integer mark) {
        this.mark = mark;
    }

    private List<StaffAccess> children = new ArrayList<>();

    public List<StaffAccess> getChildren() {
        return children;
    }

    public void setChildren(List<StaffAccess> children) {
        this.children = children;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_access.access_id
     *
     * @return the value of staff_access.access_id
     *
     * @mbggenerated
     */
    public Integer getAccessId() {
        return accessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_access.access_id
     *
     * @param accessId the value for staff_access.access_id
     *
     * @mbggenerated
     */
    public void setAccessId(Integer accessId) {
        this.accessId = accessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_access.access_name
     *
     * @return the value of staff_access.access_name
     *
     * @mbggenerated
     */
    public String getAccessName() {
        return accessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_access.access_name
     *
     * @param accessName the value for staff_access.access_name
     *
     * @mbggenerated
     */
    public void setAccessName(String accessName) {
        this.accessName = accessName == null ? null : accessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_access.access_module_id
     *
     * @return the value of staff_access.access_module_id
     *
     * @mbggenerated
     */
    public Integer getAccessModuleId() {
        return accessModuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_access.access_module_id
     *
     * @param accessModuleId the value for staff_access.access_module_id
     *
     * @mbggenerated
     */
    public void setAccessModuleId(Integer accessModuleId) {
        this.accessModuleId = accessModuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_access.url
     *
     * @return the value of staff_access.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_access.url
     *
     * @param url the value for staff_access.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_access.permissions
     *
     * @return the value of staff_access.permissions
     *
     * @mbggenerated
     */
    public String getPermissions() {
        return permissions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_access.permissions
     *
     * @param permissions the value for staff_access.permissions
     *
     * @mbggenerated
     */
    public void setPermissions(String permissions) {
        this.permissions = permissions == null ? null : permissions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_access.type
     *
     * @return the value of staff_access.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_access.type
     *
     * @param type the value for staff_access.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_access.add_time
     *
     * @return the value of staff_access.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_access.add_time
     *
     * @param addTime the value for staff_access.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_access.staff_id
     *
     * @return the value of staff_access.staff_id
     *
     * @mbggenerated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_access.staff_id
     *
     * @param staffId the value for staff_access.staff_id
     *
     * @mbggenerated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_access
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        return "StaffAccess{" +
                "accessId=" + accessId +
                ", accessName='" + accessName + '\'' +
                ", accessModuleId=" + accessModuleId +
                ", url='" + url + '\'' +
                ", permissions='" + permissions + '\'' +
                ", type=" + type +
                ", addTime=" + addTime +
                ", staffId=" + staffId +
                ", mark=" + mark +
                '}';
    }
}