package com.mingyuansoftware.aifactory.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;
@ApiModel(description="王力影")
public class StaffGroupAccess implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_group_access.group_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "权限组id", example = "1")
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_group_access.access_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "权限id", example = "1")
    private Integer accessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_group_access.add_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "新增时间", example = "2018-03-04")
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_group_access.staff_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "员工id", example = "1")
    private Integer staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table staff_group_access
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_group_access.group_id
     *
     * @return the value of staff_group_access.group_id
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_group_access.group_id
     *
     * @param groupId the value for staff_group_access.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_group_access.access_id
     *
     * @return the value of staff_group_access.access_id
     *
     * @mbggenerated
     */
    public Integer getAccessId() {
        return accessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_group_access.access_id
     *
     * @param accessId the value for staff_group_access.access_id
     *
     * @mbggenerated
     */
    public void setAccessId(Integer accessId) {
        this.accessId = accessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_group_access.add_time
     *
     * @return the value of staff_group_access.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_group_access.add_time
     *
     * @param addTime the value for staff_group_access.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_group_access.staff_id
     *
     * @return the value of staff_group_access.staff_id
     *
     * @mbggenerated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_group_access.staff_id
     *
     * @param staffId the value for staff_group_access.staff_id
     *
     * @mbggenerated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_group_access
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", groupId=").append(groupId);
        sb.append(", accessId=").append(accessId);
        sb.append(", addTime=").append(addTime);
        sb.append(", staffId=").append(staffId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}