package com.mingyuansoftware.aifactory.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.math.BigDecimal;
@ApiModel(description = "王力影")
public class SupplierGoods implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_goods.supplier_goods_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "供应商货物id", example = "1")
    private Integer supplierGoodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_goods.supplier_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "供应商id", example = "1")
    private Integer supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_goods.parts_cd
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "部品CD", example = "部品11")
    private String partsCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_goods.quantity
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "供应过的数量", example = "18")
    private BigDecimal quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_goods.product_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "品名", example = "钢球")
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_goods.specification
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "规格", example = "个")
    private String specification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_goods.is_delete
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "删除状态 1.表示删除 0.表示未删除", example = "0")
    private Byte isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplier_goods
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_goods.supplier_goods_id
     *
     * @return the value of supplier_goods.supplier_goods_id
     *
     * @mbggenerated
     */
    public Integer getSupplierGoodsId() {
        return supplierGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_goods.supplier_goods_id
     *
     * @param supplierGoodsId the value for supplier_goods.supplier_goods_id
     *
     * @mbggenerated
     */
    public void setSupplierGoodsId(Integer supplierGoodsId) {
        this.supplierGoodsId = supplierGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_goods.supplier_id
     *
     * @return the value of supplier_goods.supplier_id
     *
     * @mbggenerated
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_goods.supplier_id
     *
     * @param supplierId the value for supplier_goods.supplier_id
     *
     * @mbggenerated
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_goods.parts_cd
     *
     * @return the value of supplier_goods.parts_cd
     *
     * @mbggenerated
     */
    public String getPartsCd() {
        return partsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_goods.parts_cd
     *
     * @param partsCd the value for supplier_goods.parts_cd
     *
     * @mbggenerated
     */
    public void setPartsCd(String partsCd) {
        this.partsCd = partsCd == null ? null : partsCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_goods.quantity
     *
     * @return the value of supplier_goods.quantity
     *
     * @mbggenerated
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_goods.quantity
     *
     * @param quantity the value for supplier_goods.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_goods.product_name
     *
     * @return the value of supplier_goods.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_goods.product_name
     *
     * @param productName the value for supplier_goods.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_goods.specification
     *
     * @return the value of supplier_goods.specification
     *
     * @mbggenerated
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_goods.specification
     *
     * @param specification the value for supplier_goods.specification
     *
     * @mbggenerated
     */
    public void setSpecification(String specification) {
        this.specification = specification == null ? null : specification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_goods.is_delete
     *
     * @return the value of supplier_goods.is_delete
     *
     * @mbggenerated
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_goods.is_delete
     *
     * @param isDelete the value for supplier_goods.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_goods
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", supplierGoodsId=").append(supplierGoodsId);
        sb.append(", supplierId=").append(supplierId);
        sb.append(", partsCd=").append(partsCd);
        sb.append(", quantity=").append(quantity);
        sb.append(", productName=").append(productName);
        sb.append(", specification=").append(specification);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}