package com.mingyuansoftware.aifactory.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
@ApiModel(description = "王力影")
public class Supplier implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.supplier_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "供应商id", example = "1")
    private Integer supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.supplier_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "供应商名称", example = "供应1")
    private String supplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.contact
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "联系人", example = "小李")
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.phone
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "联系电话", example = "1456721896")
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.address
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "地址", example = "天津市")
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.payee
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "收款人", example = "小王")
    private String payee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.bank_account
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "开户行", example = "天津支行")
    private String bankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.account_number
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "银行卡号", example = "6226898822223333")
    private String accountNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.tax_number
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "税号", example = "18945271")
    private String taxNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.account_period
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "账期", example = "账期")
    private String accountPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.supplier_number
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "供应商编码", example = "18527921")
    private String supplierNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.fax
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "传真", example = "5558881")
    private String fax;

    @ApiModelProperty(value = "邮箱", example = "124@qq.com")
    private String email;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.website
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "公司网址", example = "www.baid.com")
    private String website;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.payment_method
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "付款方式", example = "打卡")
    private String paymentMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.invoice_category
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "发票类别", example = "普通发票")
    private String invoiceCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.is_delete
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "删除状态 1.表示删除 0.表示未删除", example = "0")
    private Byte isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.create_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "创建时间", example = "2018-09-04")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.update_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "修改时间", example = "2018-09-04")
    private Date updateTime;

    private BigDecimal pendingAmount;

    public BigDecimal getPendingAmount() {
        return pendingAmount;
    }

    public void setPendingAmount(BigDecimal pendingAmount) {
        this.pendingAmount = pendingAmount;
    }

    @ApiModelProperty(value = "供应商联系人", example = "供应商联系人")
    private List<SupplierContact> supplierContacts=new ArrayList<>();

    @ApiModelProperty(value = "供应商货物", example = "供应商货物")
    private List<SupplierGoods> supplierGoods =new ArrayList<>();

    public List<SupplierContact> getSupplierContacts() {
        return supplierContacts;
    }

    public void setSupplierContacts(List<SupplierContact> supplierContacts) {
        this.supplierContacts = supplierContacts;
    }

    public List<SupplierGoods> getSupplierGoods() {
        return supplierGoods;
    }

    public void setSupplierGoods(List<SupplierGoods> supplierGoods) {
        this.supplierGoods = supplierGoods;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplier
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.supplier_id
     *
     * @return the value of supplier.supplier_id
     *
     * @mbggenerated
     */


    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.supplier_id
     *
     * @param supplierId the value for supplier.supplier_id
     *
     * @mbggenerated
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.supplier_name
     *
     * @return the value of supplier.supplier_name
     *
     * @mbggenerated
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.supplier_name
     *
     * @param supplierName the value for supplier.supplier_name
     *
     * @mbggenerated
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.contact
     *
     * @return the value of supplier.contact
     *
     * @mbggenerated
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.contact
     *
     * @param contact the value for supplier.contact
     *
     * @mbggenerated
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.phone
     *
     * @return the value of supplier.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.phone
     *
     * @param phone the value for supplier.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.address
     *
     * @return the value of supplier.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.address
     *
     * @param address the value for supplier.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.payee
     *
     * @return the value of supplier.payee
     *
     * @mbggenerated
     */
    public String getPayee() {
        return payee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.payee
     *
     * @param payee the value for supplier.payee
     *
     * @mbggenerated
     */
    public void setPayee(String payee) {
        this.payee = payee == null ? null : payee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.bank_account
     *
     * @return the value of supplier.bank_account
     *
     * @mbggenerated
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.bank_account
     *
     * @param bankAccount the value for supplier.bank_account
     *
     * @mbggenerated
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.account_number
     *
     * @return the value of supplier.account_number
     *
     * @mbggenerated
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.account_number
     *
     * @param accountNumber the value for supplier.account_number
     *
     * @mbggenerated
     */
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber == null ? null : accountNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.tax_number
     *
     * @return the value of supplier.tax_number
     *
     * @mbggenerated
     */
    public String getTaxNumber() {
        return taxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.tax_number
     *
     * @param taxNumber the value for supplier.tax_number
     *
     * @mbggenerated
     */
    public void setTaxNumber(String taxNumber) {
        this.taxNumber = taxNumber == null ? null : taxNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.account_period
     *
     * @return the value of supplier.account_period
     *
     * @mbggenerated
     */
    public String getAccountPeriod() {
        return accountPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.account_period
     *
     * @param accountPeriod the value for supplier.account_period
     *
     * @mbggenerated
     */
    public void setAccountPeriod(String accountPeriod) {
        this.accountPeriod = accountPeriod == null ? null : accountPeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.supplier_number
     *
     * @return the value of supplier.supplier_number
     *
     * @mbggenerated
     */
    public String getSupplierNumber() {
        return supplierNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.supplier_number
     *
     * @param supplierNumber the value for supplier.supplier_number
     *
     * @mbggenerated
     */
    public void setSupplierNumber(String supplierNumber) {
        this.supplierNumber = supplierNumber == null ? null : supplierNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.fax
     *
     * @return the value of supplier.fax
     *
     * @mbggenerated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.fax
     *
     * @param fax the value for supplier.fax
     *
     * @mbggenerated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.website
     *
     * @return the value of supplier.website
     *
     * @mbggenerated
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.website
     *
     * @param website the value for supplier.website
     *
     * @mbggenerated
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.payment_method
     *
     * @return the value of supplier.payment_method
     *
     * @mbggenerated
     */
    public String getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.payment_method
     *
     * @param paymentMethod the value for supplier.payment_method
     *
     * @mbggenerated
     */
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod == null ? null : paymentMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.invoice_category
     *
     * @return the value of supplier.invoice_category
     *
     * @mbggenerated
     */
    public String getInvoiceCategory() {
        return invoiceCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.invoice_category
     *
     * @param invoiceCategory the value for supplier.invoice_category
     *
     * @mbggenerated
     */
    public void setInvoiceCategory(String invoiceCategory) {
        this.invoiceCategory = invoiceCategory == null ? null : invoiceCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.is_delete
     *
     * @return the value of supplier.is_delete
     *
     * @mbggenerated
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.is_delete
     *
     * @param isDelete the value for supplier.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.create_time
     *
     * @return the value of supplier.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.create_time
     *
     * @param createTime the value for supplier.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.update_time
     *
     * @return the value of supplier.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.update_time
     *
     * @param updateTime the value for supplier.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", supplierId=").append(supplierId);
        sb.append(", supplierName=").append(supplierName);
        sb.append(", contact=").append(contact);
        sb.append(", phone=").append(phone);
        sb.append(", address=").append(address);
        sb.append(", payee=").append(payee);
        sb.append(", bankAccount=").append(bankAccount);
        sb.append(", accountNumber=").append(accountNumber);
        sb.append(", taxNumber=").append(taxNumber);
        sb.append(", accountPeriod=").append(accountPeriod);
        sb.append(", supplierNumber=").append(supplierNumber);
        sb.append(", fax=").append(fax);
        sb.append(", website=").append(website);
        sb.append(", paymentMethod=").append(paymentMethod);
        sb.append(", invoiceCategory=").append(invoiceCategory);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}