package com.mingyuansoftware.aifactory.service;

import com.mingyuansoftware.aifactory.model.InventoryCheck;
import com.mingyuansoftware.aifactory.model.InventoryCheckGoods;
import com.mingyuansoftware.aifactory.model.PDAInventoryCheckTask;
import com.mingyuansoftware.aifactory.model.dto.InventoryCheckDto;

import java.math.BigDecimal;
import java.util.List;

public interface InventoryCheckService {
    int deleteByPrimaryKey(Integer inventoryCheckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_check
     *
     * @mbggenerated
     */
    int insert(InventoryCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_check
     *
     * @mbggenerated
     * @param inventoryCheckId
     */
    InventoryCheck selectByPrimaryKey(int inventoryCheckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_check
     *
     * @mbggenerated
     * @param inventoryCheckDto
     */
    List<InventoryCheck> selectAll(InventoryCheckDto inventoryCheckDto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_check
     *
     * @mbggenerated
     */
    void updateByPrimaryKey(InventoryCheck record);

    /**
     * 获取盘点操作任务列表待处理条数
     * @return
     */
    int selectPDaInventoryCheckTaskListCount();

    /**
     * 获取盘点操作任务列表
     * @return
     */
    List<PDAInventoryCheckTask> selectPDaInventoryCheckTaskList();

    /**
     * 根据盘点详情id修改货物盘点状态  pda货物盘点状态 1.未盘点 2.已盘点
     * @param staffId
     * @param inventoryCheckGoodsId
     * @param inventoryQuantity
     * @return
     */
    InventoryCheck updateInventoryCheck(Integer staffId, Integer inventoryCheckGoodsId, BigDecimal inventoryQuantity);

    /**
     * 根据货物id和盘点单id查询盘点单详情id
     * @param inventoryCheckId
     * @param goodsId
     * @return
     */
    Integer selectInventoryCheckGoodsId(Integer inventoryCheckId, Integer goodsId);

    /**
     * 根据货物Id查询库存表中的盘点的货物的库存数量
     * @param goodsId
     * @param warehouseId
     * @return
     */
    InventoryCheckGoods selectStockQuantityByGId(Integer goodsId, Integer warehouseId);
}
