package com.mingyuansoftware.aifactory.mapper;

import com.mingyuansoftware.aifactory.model.Bizdictionary;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
@Mapper
public interface BizdictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bizdictionary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bizdictionary
     *
     * @mbggenerated
     */
    int insert(Bizdictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bizdictionary
     *
     * @mbggenerated
     */
   Bizdictionary selectByPrimaryKey(Integer id);

    List<String> selectByParentKey (Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bizdictionary
     *
     * @mbggenerated
     */
    List<Bizdictionary> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bizdictionary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Bizdictionary record);

    /**
     * 根据父id查询调拨类型列表
     * @param parentId
     * @return
     */
    List<Bizdictionary> selectListByParentId(@Param("parentId") int parentId);
}