package com.mingyuansoftware.aifactory.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
@ApiModel(description = "王力影")
public class Receipt implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.receipt_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "收款单id", example = "1")
    private Integer receiptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.receipt_number
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "编号", example = "221")
    private String receiptNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.category
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "收款类别", example = "销售收款")
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.payer
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "付款方", example = "小王")
    private String payer;

    @ApiModelProperty(value = "付款方id", example = "1")
    private Integer payerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.associated_document
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "关联单据", example = "551")
    private String associatedDocument;


    @ApiModelProperty(value = "销售订单id", example = "1")
    private Integer saleId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.amount
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "单据金额", example = "1")
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.amount_receivable
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "应收金额", example = "1")
    private BigDecimal amountReceivable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.pending_write_off_amount
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "待核销金额", example = "1")
    private BigDecimal pendingWriteOffAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.collection_amount
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "收款金额", example = "1.11")
    private BigDecimal collectionAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.write_off_amount
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "核销金额", example = "1")
    private BigDecimal writeOffAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.payment_method
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "支付方式", example = "支付方式")
    private String paymentMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.comment
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "备注", example = "备注")
    private String comment;

    @ApiModelProperty(value = "创建时间", example = "2018-03-04")
    private String cjTime;

    @ApiModelProperty(value = "员工姓名", example = "员工姓名")
    private String name;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.staff_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "员工id", example = "1")
    private Integer staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.create_time
     *
     * @mbggenerated
     */

    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.update_time
     *
     * @mbggenerated
     */

    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.is_delete
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "是否删除 1是 0否", example = "")
    private Byte isDelete;

    public Integer getPayerId() {
        return payerId;
    }

    public void setPayerId(Integer payerId) {
        this.payerId = payerId;
    }

    public Integer getSaleId() {
        return saleId;
    }

    public void setSaleId(Integer saleId) {
        this.saleId = saleId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table receipt
     *
     * @mbggenerated
     */



    private static final long serialVersionUID = 1L;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCjTime() {
        return cjTime;
    }

    public void setCjTime(String cjTime) {
        this.cjTime = cjTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.receipt_id
     *
     * @return the value of receipt.receipt_id
     *
     * @mbggenerated
     */
    public Integer getReceiptId() {
        return receiptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.receipt_id
     *
     * @param receiptId the value for receipt.receipt_id
     *
     * @mbggenerated
     */
    public void setReceiptId(Integer receiptId) {
        this.receiptId = receiptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.receipt_number
     *
     * @return the value of receipt.receipt_number
     *
     * @mbggenerated
     */
    public String getReceiptNumber() {
        return receiptNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.receipt_number
     *
     * @param receiptNumber the value for receipt.receipt_number
     *
     * @mbggenerated
     */
    public void setReceiptNumber(String receiptNumber) {
        this.receiptNumber = receiptNumber == null ? null : receiptNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.category
     *
     * @return the value of receipt.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.category
     *
     * @param category the value for receipt.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.payer
     *
     * @return the value of receipt.payer
     *
     * @mbggenerated
     */
    public String getPayer() {
        return payer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.payer
     *
     * @param payer the value for receipt.payer
     *
     * @mbggenerated
     */
    public void setPayer(String payer) {
        this.payer = payer == null ? null : payer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.associated_document
     *
     * @return the value of receipt.associated_document
     *
     * @mbggenerated
     */
    public String getAssociatedDocument() {
        return associatedDocument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.associated_document
     *
     * @param associatedDocument the value for receipt.associated_document
     *
     * @mbggenerated
     */
    public void setAssociatedDocument(String associatedDocument) {
        this.associatedDocument = associatedDocument == null ? null : associatedDocument.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.amount
     *
     * @return the value of receipt.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.amount
     *
     * @param amount the value for receipt.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.amount_receivable
     *
     * @return the value of receipt.amount_receivable
     *
     * @mbggenerated
     */
    public BigDecimal getAmountReceivable() {
        return amountReceivable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.amount_receivable
     *
     * @param amountReceivable the value for receipt.amount_receivable
     *
     * @mbggenerated
     */
    public void setAmountReceivable(BigDecimal amountReceivable) {
        this.amountReceivable = amountReceivable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.pending_write_off_amount
     *
     * @return the value of receipt.pending_write_off_amount
     *
     * @mbggenerated
     */
    public BigDecimal getPendingWriteOffAmount() {
        return pendingWriteOffAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.pending_write_off_amount
     *
     * @param pendingWriteOffAmount the value for receipt.pending_write_off_amount
     *
     * @mbggenerated
     */
    public void setPendingWriteOffAmount(BigDecimal pendingWriteOffAmount) {
        this.pendingWriteOffAmount = pendingWriteOffAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.collection_amount
     *
     * @return the value of receipt.collection_amount
     *
     * @mbggenerated
     */
    public BigDecimal getCollectionAmount() {
        return collectionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.collection_amount
     *
     * @param collectionAmount the value for receipt.collection_amount
     *
     * @mbggenerated
     */
    public void setCollectionAmount(BigDecimal collectionAmount) {
        this.collectionAmount = collectionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.write_off_amount
     *
     * @return the value of receipt.write_off_amount
     *
     * @mbggenerated
     */
    public BigDecimal getWriteOffAmount() {
        return writeOffAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.write_off_amount
     *
     * @param writeOffAmount the value for receipt.write_off_amount
     *
     * @mbggenerated
     */
    public void setWriteOffAmount(BigDecimal writeOffAmount) {
        this.writeOffAmount = writeOffAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.payment_method
     *
     * @return the value of receipt.payment_method
     *
     * @mbggenerated
     */
    public String getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.payment_method
     *
     * @param paymentMethod the value for receipt.payment_method
     *
     * @mbggenerated
     */
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod == null ? null : paymentMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.comment
     *
     * @return the value of receipt.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.comment
     *
     * @param comment the value for receipt.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.staff_id
     *
     * @return the value of receipt.staff_id
     *
     * @mbggenerated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.staff_id
     *
     * @param staffId the value for receipt.staff_id
     *
     * @mbggenerated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.create_time
     *
     * @return the value of receipt.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.create_time
     *
     * @param createTime the value for receipt.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.update_time
     *
     * @return the value of receipt.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.update_time
     *
     * @param updateTime the value for receipt.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.is_delete
     *
     * @return the value of receipt.is_delete
     *
     * @mbggenerated
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.is_delete
     *
     * @param isDelete the value for receipt.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", receiptId=").append(receiptId);
        sb.append(", receiptNumber=").append(receiptNumber);
        sb.append(", category=").append(category);
        sb.append(", payer=").append(payer);
        sb.append(", associatedDocument=").append(associatedDocument);
        sb.append(", amount=").append(amount);
        sb.append(", amountReceivable=").append(amountReceivable);
        sb.append(", pendingWriteOffAmount=").append(pendingWriteOffAmount);
        sb.append(", collectionAmount=").append(collectionAmount);
        sb.append(", writeOffAmount=").append(writeOffAmount);
        sb.append(", paymentMethod=").append(paymentMethod);
        sb.append(", comment=").append(comment);
        sb.append(", staffId=").append(staffId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}