package com.mingyuansoftware.aifactory.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

@ApiModel(description = "王力影")
public class SupplierContact implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contact.supplier_contact_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "供应商联系人id", example = "1")
    private Integer supplierContactId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contact.department
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "部门", example = "部门2")
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contact.position
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "职务", example = "职员")
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contact.contact
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "联系人", example = "小王")
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contact.phone
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "电话", example = "1874693")
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contact.fax
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "传真", example = "8884444")
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contact.email
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "电子邮件", example = "124852@qq.com")
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contact.comment
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "备注", example = "1")
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contact.supplier_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "供应商id", example = "1")
    private Integer supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contact.is_delete
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "删除状态 1.表示删除 0.表示未删除", example = "0")
    private Byte isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplier_contact
     *
     * @mbggenerated
     */

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contact.supplier_contact_id
     *
     * @return the value of supplier_contact.supplier_contact_id
     *
     * @mbggenerated
     */
    public Integer getSupplierContactId() {
        return supplierContactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contact.supplier_contact_id
     *
     * @param supplierContactId the value for supplier_contact.supplier_contact_id
     *
     * @mbggenerated
     */
    public void setSupplierContactId(Integer supplierContactId) {
        this.supplierContactId = supplierContactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contact.department
     *
     * @return the value of supplier_contact.department
     *
     * @mbggenerated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contact.department
     *
     * @param department the value for supplier_contact.department
     *
     * @mbggenerated
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contact.position
     *
     * @return the value of supplier_contact.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contact.position
     *
     * @param position the value for supplier_contact.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contact.contact
     *
     * @return the value of supplier_contact.contact
     *
     * @mbggenerated
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contact.contact
     *
     * @param contact the value for supplier_contact.contact
     *
     * @mbggenerated
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contact.phone
     *
     * @return the value of supplier_contact.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contact.phone
     *
     * @param phone the value for supplier_contact.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contact.fax
     *
     * @return the value of supplier_contact.fax
     *
     * @mbggenerated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contact.fax
     *
     * @param fax the value for supplier_contact.fax
     *
     * @mbggenerated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contact.email
     *
     * @return the value of supplier_contact.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contact.email
     *
     * @param email the value for supplier_contact.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contact.comment
     *
     * @return the value of supplier_contact.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contact.comment
     *
     * @param comment the value for supplier_contact.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contact.supplier_id
     *
     * @return the value of supplier_contact.supplier_id
     *
     * @mbggenerated
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contact.supplier_id
     *
     * @param supplierId the value for supplier_contact.supplier_id
     *
     * @mbggenerated
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contact.is_delete
     *
     * @return the value of supplier_contact.is_delete
     *
     * @mbggenerated
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contact.is_delete
     *
     * @param isDelete the value for supplier_contact.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_contact
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", supplierContactId=").append(supplierContactId);
        sb.append(", department=").append(department);
        sb.append(", position=").append(position);
        sb.append(", contact=").append(contact);
        sb.append(", phone=").append(phone);
        sb.append(", fax=").append(fax);
        sb.append(", email=").append(email);
        sb.append(", comment=").append(comment);
        sb.append(", supplierId=").append(supplierId);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}