package com.mingyuansoftware.aifactory.mapper;

import com.mingyuansoftware.aifactory.model.Receipt;
import com.mingyuansoftware.aifactory.model.dto.ReceiptDto;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;
@Mapper
@Repository
public interface ReceiptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer receiptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbggenerated
     */
    int insert(Receipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbggenerated
     */
    Receipt selectByPrimaryKey(Integer receiptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbggenerated
     */
    List<Receipt> selectAll(ReceiptDto receiptDto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Receipt record);
}