package com.mingyuansoftware.aifactory.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
@ApiModel(description = "王力影")
public class Bizdictionary implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bizdictionary.id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "数据字典id", example = "1")
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bizdictionary.parent_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "父结点id", example = "1")
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bizdictionary.biz_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "结点名称", example = "长度")
    private String bizName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bizdictionary.comment
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "备注", example = "单位")
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bizdictionary.disorder
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "顺序", example = "1")
    private Integer disorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bizdictionary.value
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "结点值", example = "m")
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bizdictionary
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bizdictionary.id
     *
     * @return the value of bizdictionary.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bizdictionary.id
     *
     * @param id the value for bizdictionary.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bizdictionary.parent_id
     *
     * @return the value of bizdictionary.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bizdictionary.parent_id
     *
     * @param parentId the value for bizdictionary.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bizdictionary.biz_name
     *
     * @return the value of bizdictionary.biz_name
     *
     * @mbggenerated
     */
    public String getBizName() {
        return bizName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bizdictionary.biz_name
     *
     * @param bizName the value for bizdictionary.biz_name
     *
     * @mbggenerated
     */
    public void setBizName(String bizName) {
        this.bizName = bizName == null ? null : bizName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bizdictionary.comment
     *
     * @return the value of bizdictionary.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bizdictionary.comment
     *
     * @param comment the value for bizdictionary.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bizdictionary.disorder
     *
     * @return the value of bizdictionary.disorder
     *
     * @mbggenerated
     */
    public Integer getDisorder() {
        return disorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bizdictionary.disorder
     *
     * @param disorder the value for bizdictionary.disorder
     *
     * @mbggenerated
     */
    public void setDisorder(Integer disorder) {
        this.disorder = disorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bizdictionary.value
     *
     * @return the value of bizdictionary.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bizdictionary.value
     *
     * @param value the value for bizdictionary.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bizdictionary
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", parentId=").append(parentId);
        sb.append(", bizName=").append(bizName);
        sb.append(", comment=").append(comment);
        sb.append(", disorder=").append(disorder);
        sb.append(", value=").append(value);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}