package com.mingyuansoftware.aifactory.model.dto;

import com.mingyuansoftware.aifactory.model.InventoryCheckGoods;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class InventoryCheckDto implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_check.inventory_check_number
     *
     * @mbggenerated
     */
    private Integer inventoryCheckId;

    private String inventoryCheckNumber;


    private String fqTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_check.warehouse_id
     *
     * @mbggenerated
     */
    private String warehouseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_check.staff_id
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_check.state
     *
     * @mbggenerated
     */
    private Byte state;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inventory_check
     *
     * @mbggenerate
     */
    private String comment;

    public Integer getInventoryCheckId() {
        return inventoryCheckId;
    }

    public void setInventoryCheckId(Integer inventoryCheckId) {
        this.inventoryCheckId = inventoryCheckId;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    private static final long serialVersionUID = 1L;

    public String getFqTime() {
        return fqTime;
    }

    public void setFqTime(String fqTime) {
        this.fqTime = fqTime;
    }

    public String getWarehouseName() {
        return warehouseName;
    }

    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_check.inventory_check_number
     *
     * @return the value of inventory_check.inventory_check_number
     *
     * @mbggenerated
     */
    public String getInventoryCheckNumber() {
        return inventoryCheckNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_check.inventory_check_number
     *
     * @param inventoryCheckNumber the value for inventory_check.inventory_check_number
     *
     * @mbggenerated
     */
    public void setInventoryCheckNumber(String inventoryCheckNumber) {
        this.inventoryCheckNumber = inventoryCheckNumber == null ? null : inventoryCheckNumber.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_check.staff_id
     *
     * @return the value of inventory_check.staff_id
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_check.state
     *
     * @return the value of inventory_check.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_check.state
     *
     * @param state the value for inventory_check.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_check.create_time
     *
     * @return the value of inventory_check.create_time
     *
     * @mbggenerated
     */



}