package com.mingyuansoftware.aifactory.model.dto;

import com.mingyuansoftware.aifactory.model.ReimburseDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

@ApiModel(description = "王力影")
public class ReimburseDto implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse.reimburse_id
     *
     * @mbggenerated
     */


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse.reimburse_number
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "报销单编号", example = "581")
    private String reimburseNumber;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse.application_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "申请时间", example = "2018-03-04")
    private String applicationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse.amount
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "金额", example = "1.25")
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse.state
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "状态", example = "1")
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse.comment
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "备注", example = "122")
    private String comment;


    private String createName;


    public String getCreateName() {
        return createName;
    }

    public void setCreateName(String createName) {
        this.createName = createName;
    }


    private static final long serialVersionUID = 1L;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimburse.reimburse_number
     *
     * @return the value of reimburse.reimburse_number
     *
     * @mbggenerated
     */
    public String getReimburseNumber() {
        return reimburseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse.reimburse_number
     *
     * @param reimburseNumber the value for reimburse.reimburse_number
     *
     * @mbggenerated
     */
    public void setReimburseNumber(String reimburseNumber) {
        this.reimburseNumber = reimburseNumber == null ? null : reimburseNumber.trim();
    }


    public String getApplicationTime() {
        return applicationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse.application_time
     *
     * @param applicationTime the value for reimburse.application_time
     *
     * @mbggenerated
     */
    public void setApplicationTime(String applicationTime) {
        this.applicationTime = applicationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimburse.amount
     *
     * @return the value of reimburse.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse.amount
     *
     * @param amount the value for reimburse.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimburse.state
     *
     * @return the value of reimburse.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse.state
     *
     * @param state the value for reimburse.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimburse.comment
     *
     * @return the value of reimburse.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse.comment
     *
     * @param comment the value for reimburse.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }


}