package com.mingyuansoftware.aifactory.mapper;

import com.mingyuansoftware.aifactory.model.AdjustRecord;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
@Mapper
public interface AdjustRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjust_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjust_record
     *
     * @mbggenerated
     */
    int insert(AdjustRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjust_record
     *
     * @mbggenerated
     */
    List<AdjustRecord> selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjust_record
     *
     * @mbggenerated
     */
    List<AdjustRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjust_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdjustRecord record);
}