package com.mingyuansoftware.aifactory.mapper;

import com.mingyuansoftware.aifactory.model.InventoryCheck;
import com.mingyuansoftware.aifactory.model.PDAInventoryCheckTask;
import com.mingyuansoftware.aifactory.model.dto.InventoryCheckDto;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
@Mapper
public interface InventoryCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_check
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer inventoryCheckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_check
     *
     * @mbggenerated
     */
    int insert(InventoryCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_check
     *
     * @mbggenerated
     */
    InventoryCheck selectByPrimaryKey(Integer inventoryCheckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_check
     *
     * @mbggenerated
     * @param inventoryCheckDto
     */
    List<InventoryCheck> selectAll(InventoryCheckDto inventoryCheckDto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_check
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InventoryCheck record);

    /**
     * 获取盘点操作任务列表待处理条数
     * @return
     */
    int selectPDaInventoryCheckTaskListCount();

    /**
     * 获取盘点操作任务列表
     * @return
     */
    List<PDAInventoryCheckTask> selectPDaInventoryCheckTaskList();

    /**
     * 修改盘点单盘点状态
     * @param inventoryCheckId
     * @param state
     * @param staffId
     */
    void updateStateById(@Param("inventoryCheckId") Integer inventoryCheckId,@Param("state") int state,@Param("staffId") Integer staffId);
}