package com.mingyuansoftware.aifactory.mapper;

import com.mingyuansoftware.aifactory.model.ReimburseDetails;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
@Mapper
public interface ReimburseDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reimburse_details
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer reimburseDetailsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reimburse_details
     *
     * @mbggenerated
     */
    int insert(ReimburseDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reimburse_details
     *
     * @mbggenerated
     */
    List<ReimburseDetails> selectByPrimaryKey(Integer reimburseDetailsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reimburse_details
     *
     * @mbggenerated
     */
    List<ReimburseDetails> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reimburse_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReimburseDetails record);
}