package com.mingyuansoftware.aifactory.mapper;

import com.mingyuansoftware.aifactory.model.Reimburse;
import com.mingyuansoftware.aifactory.model.dto.ReimburseDto;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
@Mapper
public interface ReimburseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reimburse
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer reimburseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reimburse
     *
     * @mbggenerated
     */
    int insert(Reimburse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reimburse
     *
     * @mbggenerated
     */
    Reimburse selectByPrimaryKey(Integer reimburseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reimburse
     *
     * @mbggenerated
     * @param reimburseDto
     */
    List<Reimburse> selectAll(ReimburseDto reimburseDto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reimburse
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Reimburse record);

    /**
     * 根据员工Id获取报销单信息(包括编号,金额)
     * @param staffId
     * @return
     */
    List<Reimburse> selectListByStaffId(@Param("staffId") int staffId);

    /**
     * 根据报销单编号修改报销付款内容
     * @param reimburseDto
     */
    void updateByNumber(@Param("reimburseDto") ReimburseDto reimburseDto);
}