package com.mingyuansoftware.aifactory.mapper;

import com.mingyuansoftware.aifactory.model.StaffAccessGroup;
import com.mingyuansoftware.aifactory.model.StaffGroupAccess;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface StaffGroupAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_group_access
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("groupId") Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_group_access
     *
     * @mbggenerated
     * @param record
     */
    int insert(StaffAccessGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_group_access
     *
     * @mbggenerated
     */
    StaffGroupAccess selectByPrimaryKey(@Param("groupId") Integer groupId, @Param("accessId") Integer accessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_group_access
     *
     * @mbggenerated
     */
    List<StaffGroupAccess> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_group_access
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaffGroupAccess record);

    void deleteByAccessId(@Param("accessId") int accessId);
}