package com.mingyuansoftware.aifactory.mapper;

import com.mingyuansoftware.aifactory.model.StaffAccess;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
@Mapper
public interface StaffAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_access
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer accessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_access
     *
     * @mbggenerated
     */
    int insert(StaffAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_access
     *
     * @mbggenerated
     */
    StaffAccess selectByPrimaryKey(Integer accessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_access
     *
     * @mbggenerated
     */
    List<StaffAccess> selectAll();

    List<StaffAccess> selectByParId(Integer accessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_access
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaffAccess record);

    List<StaffAccess> selectByGroupId(Integer groupId);


}