package com.mingyuansoftware.aifactory.service;

import com.mingyuansoftware.aifactory.model.Receipt;
import com.mingyuansoftware.aifactory.model.dto.ReceiptDto;

import java.util.List;

public interface ReceiptService {

    int deleteByPrimaryKey(Integer receiptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbggenerated
     */
    int insert(Receipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbggenerated
     */
    Receipt selectByPrimaryKey(Integer receiptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbggenerated
     */
    List<Receipt> selectAll(ReceiptDto receiptDto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Receipt record);
}
