package com.mingyuansoftware.aifactory.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
@ApiModel(description = "王力影")
public class ReimburseDetails implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse_details.reimburse_details_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "报销单详情id", example = "1")
    private Integer reimburseDetailsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse_details.book_number
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "禀议书号码", example = "1")
    private String bookNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse_details.cost_period
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "费用日期", example = "2019-05-06")
    private String costPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse_details.use
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "用途", example = "1")
    private String use;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse_details.amount
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "金额", example = "8.31")
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse_details.comment
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "备注", example = "1")
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimburse_details.reimburse_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "报销单id", example = "1")
    private Integer reimburseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reimburse_details
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimburse_details.reimburse_details_id
     *
     * @return the value of reimburse_details.reimburse_details_id
     *
     * @mbggenerated
     */
    public Integer getReimburseDetailsId() {
        return reimburseDetailsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse_details.reimburse_details_id
     *
     * @param reimburseDetailsId the value for reimburse_details.reimburse_details_id
     *
     * @mbggenerated
     */
    public void setReimburseDetailsId(Integer reimburseDetailsId) {
        this.reimburseDetailsId = reimburseDetailsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimburse_details.book_number
     *
     * @return the value of reimburse_details.book_number
     *
     * @mbggenerated
     */
    public String getBookNumber() {
        return bookNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse_details.book_number
     *
     * @param bookNumber the value for reimburse_details.book_number
     *
     * @mbggenerated
     */
    public void setBookNumber(String bookNumber) {
        this.bookNumber = bookNumber == null ? null : bookNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimburse_details.cost_period
     *
     * @return the value of reimburse_details.cost_period
     *
     * @mbggenerated
     */
    public String getCostPeriod() {
        return costPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse_details.cost_period
     *
     * @param costPeriod the value for reimburse_details.cost_period
     *
     * @mbggenerated
     */
    public void setCostPeriod(String costPeriod) {
        this.costPeriod = costPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimburse_details.use
     *
     * @return the value of reimburse_details.use
     *
     * @mbggenerated
     */
    public String getUse() {
        return use;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse_details.use
     *
     * @param use the value for reimburse_details.use
     *
     * @mbggenerated
     */
    public void setUse(String use) {
        this.use = use == null ? null : use.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimburse_details.amount
     *
     * @return the value of reimburse_details.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse_details.amount
     *
     * @param amount the value for reimburse_details.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimburse_details.comment
     *
     * @return the value of reimburse_details.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse_details.comment
     *
     * @param comment the value for reimburse_details.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimburse_details.reimburse_id
     *
     * @return the value of reimburse_details.reimburse_id
     *
     * @mbggenerated
     */
    public Integer getReimburseId() {
        return reimburseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimburse_details.reimburse_id
     *
     * @param reimburseId the value for reimburse_details.reimburse_id
     *
     * @mbggenerated
     */
    public void setReimburseId(Integer reimburseId) {
        this.reimburseId = reimburseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reimburse_details
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", reimburseDetailsId=").append(reimburseDetailsId);
        sb.append(", bookNumber=").append(bookNumber);
        sb.append(", costPeriod=").append(costPeriod);
        sb.append(", use=").append(use);
        sb.append(", amount=").append(amount);
        sb.append(", comment=").append(comment);
        sb.append(", reimburseId=").append(reimburseId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}