package com.mingyuansoftware.aifactory.mapper;

import com.mingyuansoftware.aifactory.model.StaffAccessGroup;
import com.mingyuansoftware.aifactory.model.dto.StaffAccessGroupDto;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
@Mapper
public interface StaffAccessGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_access_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_access_group
     *
     * @mbggenerated
     */
    int insert(StaffAccessGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_access_group
     *
     * @mbggenerated
     */
    StaffAccessGroup selectByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_access_group
     *
     * @mbggenerated
     * @param staffAccessGroupDto
     */
    List<StaffAccessGroup> selectAll(StaffAccessGroupDto staffAccessGroupDto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_access_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaffAccessGroup record);

    List<StaffAccessGroup> selectList();
}