package com.mingyuansoftware.aifactory.mapper;

import com.mingyuansoftware.aifactory.model.Supplier;
import com.mingyuansoftware.aifactory.model.dto.SupplierDto;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.util.List;
@Repository
@Mapper
public interface SupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated
     */
    int insert(Supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated
     */
    Supplier selectByPrimaryKey(Integer supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated
     */
    List<Supplier> selectAll();

    List<Supplier> selectByPage( SupplierDto supplierDto);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Supplier record);

    /**
     * 获取供应商姓名列表
     * @return
     */
    List<Supplier> selectSupplierNameList();

    /**
     * 根据供应商Id修改核销金额(核销金额-核销金额(付款))
     * @param supplierId
     * @param writeOffAmount
     */
    void updateWriteOffAmountBySId(@Param("supplierId") Integer supplierId,@Param("writeOffAmount") BigDecimal writeOffAmount);

    /**
     * 根据供应商Id添加核销金额(应收金额)
     * @param supplierId
     * @param subtract
     */
    void updatePendingAmountBySId(@Param("supplierId") Integer supplierId, @Param("subtract") BigDecimal subtract);
}